#!/bin/bash
set -e

# Default behavior is to do everything from scratch.
# The --use-cache option is useful if you're iterating on a broken build.
if [[ "$1" ==  "--use-cache" ]]; then
    docker build --rm -t kaggle/python-build .
else
    docker build --pull --rm --no-cache -t kaggle/python-build .
fi
